# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from saas_identity_platform_fastapi.models.sys_user import SysUser
from saas_identity_platform_fastapi.models.tenant_membership import TenantMembership
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class LoginResponse(BaseModel):
    """
    LoginResponse
    """ # noqa: E501
    user: SysUser
    available_tenants: List[TenantMembership] = Field(alias="availableTenants")
    user_id: UUID = Field(alias="userId")
    current_tenant_id: Optional[UUID] = Field(default=None, alias="currentTenantId")
    access_token: Optional[StrictStr] = Field(default=None, alias="accessToken")
    refresh_token: Optional[StrictStr] = Field(default=None, alias="refreshToken")
    token_type: Optional[StrictStr] = Field(default=None, alias="tokenType")
    expires_in: Optional[StrictInt] = Field(default=None, alias="expiresIn")
    client_id: StrictStr = Field(alias="clientId")
    __properties: ClassVar[List[str]] = ["user", "availableTenants", "userId", "currentTenantId", "accessToken", "refreshToken", "tokenType", "expiresIn", "clientId"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LoginResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in available_tenants (list)
        _items = []
        if self.available_tenants:
            for _item in self.available_tenants:
                if _item:
                    _items.append(_item.to_dict())
            _dict['availableTenants'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of LoginResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user": SysUser.from_dict(obj.get("user")) if obj.get("user") is not None else None,
            "availableTenants": [TenantMembership.from_dict(_item) for _item in obj.get("availableTenants")] if obj.get("availableTenants") is not None else None,
            "userId": obj.get("userId"),
            "currentTenantId": obj.get("currentTenantId"),
            "accessToken": obj.get("accessToken"),
            "refreshToken": obj.get("refreshToken"),
            "tokenType": obj.get("tokenType"),
            "expiresIn": obj.get("expiresIn"),
            "clientId": obj.get("clientId")
        })
        return _obj


