# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OAuthClient(BaseModel):
    """
    OAuthClient
    """ # noqa: E501
    id: UUID
    client_id: StrictStr = Field(alias="clientId")
    client_name: StrictStr = Field(alias="clientName")
    grant_types: StrictStr = Field(alias="grantTypes")
    redirect_uris: StrictStr = Field(alias="redirectUris")
    scopes: Optional[StrictStr] = None
    access_token_validity: StrictInt = Field(alias="accessTokenValidity")
    refresh_token_validity: StrictInt = Field(alias="refreshTokenValidity")
    auto_approve: StrictBool = Field(alias="autoApprove")
    status: StrictInt
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "clientId", "clientName", "grantTypes", "redirectUris", "scopes", "accessTokenValidity", "refreshTokenValidity", "autoApprove", "status", "createdAt", "updatedAt"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OAuthClient from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OAuthClient from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "clientId": obj.get("clientId"),
            "clientName": obj.get("clientName"),
            "grantTypes": obj.get("grantTypes"),
            "redirectUris": obj.get("redirectUris"),
            "scopes": obj.get("scopes"),
            "accessTokenValidity": obj.get("accessTokenValidity"),
            "refreshTokenValidity": obj.get("refreshTokenValidity"),
            "autoApprove": obj.get("autoApprove"),
            "status": obj.get("status"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


