# coding: utf-8

"""
    (title)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from saas_identity_platform_fastapi.models.sys_menu_type import SysMenuType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class UpdateSysMenuRequest(BaseModel):
    """
    UpdateSysMenuRequest
    """ # noqa: E501
    parent_id: Optional[UUID] = Field(default=None, alias="parentId")
    title: Optional[StrictStr] = None
    type: Optional[SysMenuType] = None
    path: Optional[StrictStr] = None
    component: Optional[StrictStr] = None
    perms: Optional[StrictStr] = None
    icon: Optional[StrictStr] = None
    sort_order: Optional[StrictInt] = Field(default=None, alias="sortOrder")
    status: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["parentId", "title", "type", "path", "component", "perms", "icon", "sortOrder", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpdateSysMenuRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of UpdateSysMenuRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parentId": obj.get("parentId"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "path": obj.get("path"),
            "component": obj.get("component"),
            "perms": obj.get("perms"),
            "icon": obj.get("icon"),
            "sortOrder": obj.get("sortOrder"),
            "status": obj.get("status")
        })
        return _obj


